### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by siberian1967** [gtjoseph/mikronode-ng#1]
Hi! Thanks for forking this, much appreciated!

For both mikronode and mikronode-ng I am having trouble authenticating. It looks like the hash value is incorrect but I can not confirmed.

Various PHP and Java libs work fine, this problem only seems to impact mikronode. Tested against 6.34.4 and 6.35.2 and credentials are confirmed multiple times by testing other language apis. Below is my transcript. Any ideas?

> Johns-MacBook-Pro-2:smart.network jarmstrong$ nodemon app.js
> 9 May 19:43:54 - [nodemon] v0.7.10
> 9 May 19:43:54 - [nodemon] to restart at any time, enter `rs`
> 9 May 19:43:54 - [nodemon] watching: /Users/jarmstrong/Documents/smart.network
> 9 May 19:43:54 - [nodemon] starting `node app.js`
> Initializing mikrotek connection
> PORT:8728
> HOST192.168.88.1
> USERadmin
> PASSsonyadog
> DEBUG99
> DEBUG: Connecting to 192.168.88.1
> (node:4626) DeprecationWarning: util.debug is deprecated. Use console.error instead.
> Example app listening on port 9000!
> DEBUG: LoginHandler: Connecting : 192.168.88.1
> DEBUG: Sending Login
> DEBUG: write: sending /login
> 0: 05 21 64 6f 6e 65 25 3d    .!done%=
> 8: 72 65 74 3d 31 38 65 62    ret=18eb
> 16: 31 65 36 32 64 33 33 64    1e62d33d
> 24: 31 34 64 38 62 66 39 38    14d8bf98
> 32: 32 34 39 31 31 30 65 39    249110e9
> 35 32 65 64 00    52ed.
> DEBUG: read: data-len:45
> DEBUG: read: data-len:44
> DEBUG: read:consume len:(5) data: !done%=ret=18eb1e62d33d14d8bf98249110e952ed
> DEBUG: LoginHandler: Sending Login : 192.168.88.1
> DEBUG: Got !done. Need challenge
> DEBUG: read: data-len:38
> DEBUG: read:consume len:(37) data: =ret=18eb1e62d33d14d8bf98249110e952ed
> DEBUG: LoginHandler: Sending Login : 192.168.88.1
> DEBUG: Got challenge
> DEBUG: Sending Credentials
> DEBUG: write: sending /login
> DEBUG: write: sending =name=admin
> DEBUG: write: sending =response=00ccff5088b2a7f6a70456ea72a7bafaf3
> 0: 05 21 74 72 61 70 16 3d    .!trap=
> 8: 6d 65 73 73 61 67 65 3d    message=
> 16: 63 61 6e 6e 6f 74 20 6c    cannot l
> 24: 6f 67 20 69 6e 00 05 21    og in..!
> 64 6f 6e 65 00    done.
> DEBUG: read: data-len:37
> DEBUG: read: data-len:36
> DEBUG: read:consume len:(5) data: !trap=message=cannot log in!done
> DEBUG: LoginHandler: Sending Credentials : 192.168.88.1
> DEBUG: read: data-len:30
> DEBUG: read:consume len:(22) data: =message=cannot log in!done
> DEBUG: LoginHandler: Sending Credentials : 192.168.88.1
> DEBUG: read: data-len:7
> DEBUG: read: data-len:6
> DEBUG: read:consume len:(5) data: !done
> DEBUG: LoginHandler: Sending Credentials : 192.168.88.1
> DEBUG: Socket Timeout

**Comment by gtjoseph** [comment]
Wow, something must have changed in ROS recently.  I can't log into my own router.
I'll try and track this down tomorrow.

Hmmm....  Just tried logging into my test router which is still at 6.32.1 and it fails as well.
I must have done something stupid. :)

**Comment by gtjoseph** [comment]
Ah Ha!.  I'll bet you're running NodeJS 6.x which is also what I'm running.  When I revert to 5.8 everything works as expected.   So now I have to figure out what changed in 6.x.

If you're not running 6.x, let me know.

**Comment by siberian1967** [comment]
Yup! 6.0.0. I'll see if I can drop back.

Nice find, thanks George! Will keep my eyes peeled for a v6 fix and if I
can help let me know.
John-
ᐧ

On Tue, May 10, 2016 at 5:37 AM, George Joseph notifications@github.com
wrote:

> Ah Ha!. I'll bet you're running NodeJS 6.x which is also what I'm running.
> When I revert to 5.8 everything works as expected. So now I have to figure
> out what changed in 6.x.
> 
> If you're not running 6.x, let me know.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/f5eng/mikronode-ng/issues/1#issuecomment-218144257

##

**Comment by gtjoseph** [comment]
Check out v1.0.5.  This should fix the login issue.  It worked for me but let me know.

**Comment by ppmathis** [comment]
I had the same problem as I downloaded mikronode-ng from npm. As soon as I switched to release v1.0.5 (which is not published on npm yet), the login problems went away. Thanks a lot for fixing it!

**Comment by gtjoseph** [comment]
Sorry.  I forgot to publish it!  Published now.
