### ISSUE TITLE
118 packets p/ second -  7139 bytes p/ second with keepAlive

### ISSUE THREAD

**Issue by eduardomazolini** [gtjoseph/mikronode-ng#17]
In connection.js line 530 has "_(this).socket.setKeepAlive(true);"

Please change to false or set any delay 1s or 2s.

I use:
_(this).socket.setKeepAlive(true,2000);

**Comment by gtjoseph** [comment]
I'll get this updated this weekend.

**Comment by gtjoseph** [comment]
v1.0.10 pushed.
