### ISSUE TITLE
closeOnDone not working

### ISSUE THREAD

**Issue by craftbyte** [gtjoseph/mikronode-ng#2]
When I use getConnectPromise, the connection doesn't close even though the closeOnDone pref is set.

Code: https://gist.github.com/craftbyte/6807882d1bb651b379c6a52cc105a7ce

**Comment by craftbyte** [comment]
Solved by only making one connect promise on app launch and setting it to a global variable.
Don't forget to set closeOnDone to false for that.

**Comment by gtjoseph** [comment]
I love when people close their own issues. :)

Definitely re-open the issue if you find it's still not working.
