### ISSUE TITLE
Problem with one of examples

### ISSUE THREAD

**Issue by ssbaksa** [gtjoseph/mikronode-ng#5]
Hi,
I am new to nodejs + mikrotik pair an I am trying to learn as much as I can.
Some of examples are running correctly but I have found some errors.
First one.
In example "Simplifying the above by reducing the number of channels."
 _packet=api.parseItems([data])[0];_
should be replaced by:
 _packet=MikroNode.parseItems([data])[0];_

After that is done program runs and get's the data but there is another error.

_/root/node_modules/mikronode-ng/lib/connection.js:244
                                var l = data.shift().split(/=/);_

_TypeError: data.shift(...).split is not a function
    at /root/node_modules/mikronode-ng/lib/connection.js:244:26
    at Array.forEach (native)
    at Object.parseItems (/root/node_modules/mikronode-ng/lib/connection.js:242:8)
    at Channel.<anonymous> (/root/test2a-mt.js:10:28)
    at emitTwo (events.js:87:13)
    at Channel.emit (events.js:172:7)
    at Channel._data (/root/node_modules/mikronode-ng/lib/channel.js:358:8)
    at Connection.sentence (/root/node_modules/mikronode-ng/lib/connection.js:363:48)
    at Connection._read (/root/node_modules/mikronode-ng/lib/connection.js:409:11)
    at Socket.<anonymous> (/root/node_modules/mikronode-ng/lib/connection.js:491:10)_

Data from MikroTik is:

_parseItems: [["!re","=ret=09fc94d165ffee8a05cbdadcedd21bdf"]]
parseItems: [[]]
parseItems: [["!re","=.id=_1","=name=ether1","=default-name=ether1","=type=ether","=mtu=1500","=actual-mtu=1500","=l2mtu=1598","=max-l2mtu=4074","=mac-address=00:0C:42:A3:53:4E","=fast-path=true","=last-link-up-time=jun/30/2016 10:24:10","=link-downs=0","=rx-byte=29359708","=tx-byte=5426227","=rx-packet=348487","=tx-packet=30467","=rx-drop=0","=tx-drop=0","=rx-error=0","=tx-error=0","=fp-rx-byte=27965820","=fp-tx-byte=5271209","=fp-rx-packet=348488","=fp-tx-packet=30467","=running=true","=disabled=false","!re","=.id=_2","=name=ether2","=default-name=ether2","=type=ether","=mtu=1500","=actual-mtu=1500","=l2mtu=1598","=max-l2mtu=4074","=mac-address=00:0C:42:A3:53:4F","=fast-path=true","=link-downs=0","=rx-byte=0","=tx-byte=0","=rx-packet=0","=tx-packet=0","=rx-drop=0","=tx-drop=0","=rx-error=0","=tx-error=0","=fp-rx-byte=0","=fp-tx-byte=0","=fp-rx-packet=0","=fp-tx-packet=0","=running=false","=disabled=false","!re","=.id=_3","=name=ether3","=default-name=ether3","=type=ether","=mtu=1500","=actual-mtu=1500","=l2mtu=1598","=max-l2mtu=4074","=mac-address=00:0C:42:A3:53:50","=fast-path=true","=link-downs=0","=rx-byte=0","=tx-byte=0","=rx-packet=0","=tx-packet=0","=rx-drop=0","=tx-drop=0","=rx-error=0","=tx-error=0","=fp-rx-byte=0","=fp-tx-byte=0","=fp-rx-packet=0","=fp-tx-packet=0","=running=false","=disabled=false","!re","=.id=_4","=name=ether4","=default-name=ether4","=type=ether","=mtu=1500","=actual-mtu=1500","=l2mtu=1598","=max-l2mtu=4074","=mac-address=00:0C:42:A3:53:51","=fast-path=true","=link-downs=0","=rx-byte=0","=tx-byte=0","=rx-packet=0","=tx-packet=0","=rx-drop=0","=tx-drop=0","=rx-error=0","=tx-error=0","=fp-rx-byte=0","=fp-tx-byte=0","=fp-rx-packet=0","=fp-tx-packet=0","=running=false","=slave=true","=disabled=false","!re","=.id=*5","=name=ether5","=default-name=ether5","=type=ether","=mtu=1500","=actual-mtu=1500","=l2mtu=1598","=max-l2mtu=4074","=mac-address=00:0C:42:A3:53:52","=fast-path=true","=link-downs=0","=rx-byte=0","=tx-byte=0","=rx-packet=0","=tx-packet=0","=rx-drop=0","=tx-drop=0","=rx-error=0","=tx-error=0","=fp-rx-byte=0","=fp-tx-byte=0","=fp-rx-packet=0","=fp-tx-packet=0","=running=false","=disabled=false"]]_

When I have tured on debug line I also have this written but this is easy to fix:

_root@ub64:~# node test2a-mt.js
(node) util.puts is deprecated. Use console.log instead._

**Comment by gtjoseph** [comment]
Ha!  I guess I never updated the Readme examples.  Good catch!

I'll have them updated by the end of the day.

**Comment by gtjoseph** [comment]
Fixed in 1.0.7.
