### ISSUE TITLE
When two commands are sent through channel only last one is displayed by listen

### ISSUE THREAD

**Issue by ssbaksa** [gtjoseph/mikronode-ng#7]
I have used one of examples but results where strange. Only effect from last command was shown by listen part so I decided to dissect this example. The commands are successfully applied on Mikrotik as expected but output from listen shows only last one. To troubleshoot I have introduced sleep package and at first set delay to 3 seconds. Immediately both changes have been displayed as expected. Playing with sleep time I have fond that anything less than 0,21 (sleep.usleep(210000);) sec affects proper output. sleep.usleep(205000); is the same as no delay at all. I didn't have more time today to go through wireshark snoops which I have collected to see is there proper answer from Mikrotik or not in both cases. If tehere is then maybe mikronode is to be blamed. I am not sure at this time.

I will include both tests within this report. Wireshark snoops and screen-shots also.

Without sleep:
Interface change: [{".id":"*5","name":"ether5","default-name":"ether5","type":"ether","mtu":"1500","actual-mtu":"1500","l2mtu":"1598","max-l2mtu":"4074","mac-address":"00:0C:42:A3:53:52","fast-path":"true","link-downs":"0","running":"false","disabled":"false"}]

With sleep time at least set to 0,21 sec:
Interface change: [{".id":"_5","name":"ether5","default-name":"ether5","type":"ether","mtu":"1500","actual-mtu":"1500","l2mtu":"1598","max-l2mtu":"4074","mac-address":"00:0C:42:A3:53:52","fast-path":"true","link-downs":"0","running":"false","disabled":"true"}]
Interface change: [{".id":"_5","name":"ether5","default-name":"ether5","type":"ether","mtu":"1500","actual-mtu":"1500","l2mtu":"1598","max-l2mtu":"4074","mac-address":"00:0C:42:A3:53:52","fast-path":"true","link-downs":"0","running":"false","disabled":"false"}]  

[NODE-MT.zip](https://github.com/f5eng/mikronode-ng/files/364560/NODE-MT.zip)

**Comment by gtjoseph** [comment]
The reason you're only seeing 1 event is that although the commands were issued synchronously, the mikrotik processes the events asynchronously.  I.E.  When first command runs, the mikrotik isn't immediately sending the event, it just triggers an event to be sent.  By the time the event is actually sent, the second command has run to re-enable the interface so the event shows the interface as disabled=false.

I don't know if this is a mikrotik bug or feature but i'm going to bring it up on their forum and see.

**Comment by ssbaksa** [comment]
Hi,

This kind of behavior is not "nice" Normally, I wouldn't send two (or more) commands in sequence in a way that there is no time space between them because there is no need for such thing but it is not good for system altogether. If you have more users doing some changes then you will never know in which sequence data will be presented to them. It can be confusing. From my point of view FIFO (well, kind of) is the best way of processing the data and sending output.

Yes, please, bring it up on forum.

**Comment by gtjoseph** [comment]
I posted this on the forums and if there's no useful reply, I'll open a support ticket with Mikrotik.
[http://forum.mikrotik.com/viewtopic.php?f=9&t=110320#p547715](url)

**Comment by gtjoseph** [comment]
Finally got a response from MikroTik Support...

`If interface state changed few times, message contains only 1 interface change.
It is done to protect router from extensive writes and keep it from out of
memory. We will consider adding some specific counter or similar, for most
important events (like interface change) and notify it by API call`

Not much we can do now.
