### ISSUE TITLE
Crash in connection.js at Connection.prototype.close

### ISSUE THREAD

**Issue by germon** [gtjoseph/mikronode-ng#9]
The wrong attribute is referenced when force closing channels, probably a typo.
Line 712:
_(_this).channel[e].close(true);
Should be:
_(_this).channel**s**[e].close(true);

**Comment by gtjoseph** [comment]
Oops.  Fix committed and published version 1.0.9.

**Comment by germon** [comment]
Super fast super cool.
Thx!
